#!/bin/bash

rm -rf build/*
mkdir -p build

node_modules/.bin/tsc \
  --module commonjs \
  --noImplicitAny \
  --noEmitOnError \
  --removeComments \
  --noFallthroughCasesInSwitch \
  --outDir build src/*
