#!/bin/bash -eu

if grep -rq 'describe\.only' ./test
  then
    echo "describe.only found. Please update your test"
    exit 1
fi

if grep -rq 'it\.only' ./test
  then
    echo "it.only found. Please update your test"
    exit 1
fi

./prepublish

mocha \
  test/basics.mocha.js \
  ;
