#!/bin/bash -e

wget https://search.maven.org/remotecontent?filepath=mysql/mysql-connector-java/5.1.36/mysql-connector-java-5.1.36.jar -O test/jdbc/jar/mysql-connector-java-5.1.36.jar
wget https://search.maven.org/remotecontent?filepath=mysql/mysql-connector-java/5.1.39/mysql-connector-java-5.1.39.jar -O test/jdbc/jar/mysql-connector-java-5.1.39.jar
wget https://search.maven.org/remotecontent?filepath=mysql/mysql-connector-java/6.0.2/mysql-connector-java-6.0.2.jar -O test/jdbc/jar/mysql-connector-java-6.0.2.jar
