/*
 * Copyright 2015-2016 Imply Data, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Dataset, PlyType, External } from "plywood";

const DB_NAME = 'plyql1';

interface SchemataRow {
  "CATALOG_NAME": string;
  "SCHEMA_NAME": string;
  "DEFAULT_CHARACTER_SET_NAME": string;
  "DEFAULT_COLLATION_NAME": string;
  "SQL_PATH": string;
}

let schemataData: SchemataRow[] = [
  {
    "CATALOG_NAME": "def",
    "SCHEMA_NAME": "information_schema",
    "DEFAULT_CHARACTER_SET_NAME": "utf8",
    "DEFAULT_COLLATION_NAME": "utf8_general_ci",
    "SQL_PATH": null
  },
  {
    "CATALOG_NAME": "def",
    "SCHEMA_NAME": DB_NAME,
    "DEFAULT_CHARACTER_SET_NAME": "utf8",
    "DEFAULT_COLLATION_NAME": "utf8_general_ci",
    "SQL_PATH": null
  }
];

interface TablesRow {
  TABLE_CATALOG: string;
  TABLE_SCHEMA: string;
  TABLE_NAME: string;
  TABLE_TYPE: string;
  ENGINE: string;
  VERSION: number;
  ROW_FORMAT: string;
  TABLE_ROWS: number;
  AVG_ROW_LENGTH: number;
  DATA_LENGTH: number;
  MAX_DATA_LENGTH: number;
  INDEX_LENGTH: number;
  DATA_FREE: number;
  AUTO_INCREMENT: number;
  CREATE_TIME: Date;
  UPDATE_TIME: Date;
  CHECK_TIME: Date;
  TABLE_COLLATION: string;
  CHECKSUM: number;
  CREATE_OPTIONS: string;
  TABLE_COMMENT: string;
}

let tablesData: TablesRow[] = [
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "COLUMNS",
    "TABLE_TYPE": "SYSTEM VIEW",
    "ENGINE": "InnoDB",
    "VERSION": 10,
    "ROW_FORMAT": "Dynamic",
    "TABLE_ROWS": null,
    "AVG_ROW_LENGTH": 0,
    "DATA_LENGTH": 16384,
    "MAX_DATA_LENGTH": 0,
    "INDEX_LENGTH": 0,
    "DATA_FREE": 141557760,
    "AUTO_INCREMENT": null,
    "CREATE_TIME": null,
    "UPDATE_TIME": null,
    "CHECK_TIME": null,
    "TABLE_COLLATION": "utf8_general_ci",
    "CHECKSUM": null,
    "CREATE_OPTIONS": "max_rows=2789",
    "TABLE_COMMENT": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "SCHEMATA",
    "TABLE_TYPE": "SYSTEM VIEW",
    "ENGINE": "MEMORY",
    "VERSION": 10,
    "ROW_FORMAT": "Fixed",
    "TABLE_ROWS": null,
    "AVG_ROW_LENGTH": 3464,
    "DATA_LENGTH": 0,
    "MAX_DATA_LENGTH": 16738048,
    "INDEX_LENGTH": 0,
    "DATA_FREE": 0,
    "AUTO_INCREMENT": null,
    "CREATE_TIME": null,
    "UPDATE_TIME": null,
    "CHECK_TIME": null,
    "TABLE_COLLATION": "utf8_general_ci",
    "CHECKSUM": null,
    "CREATE_OPTIONS": "max_rows=4843",
    "TABLE_COMMENT": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "TABLES",
    "TABLE_TYPE": "SYSTEM VIEW",
    "ENGINE": "MEMORY",
    "VERSION": 10,
    "ROW_FORMAT": "Fixed",
    "TABLE_ROWS": null,
    "AVG_ROW_LENGTH": 9441,
    "DATA_LENGTH": 0,
    "MAX_DATA_LENGTH": 16757775,
    "INDEX_LENGTH": 0,
    "DATA_FREE": 0,
    "AUTO_INCREMENT": null,
    "CREATE_TIME": null,
    "UPDATE_TIME": null,
    "CHECK_TIME": null,
    "TABLE_COLLATION": "utf8_general_ci",
    "CHECKSUM": null,
    "CREATE_OPTIONS": "max_rows=1777",
    "TABLE_COMMENT": ''
  }
];

function addExternalToTables(source: string): void {
  tablesData.push({
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": DB_NAME,
    "TABLE_NAME": source,
    "TABLE_TYPE": "BASE TABLE",
    "ENGINE": "InnoDB",
    "VERSION": 10,
    "ROW_FORMAT": "Dynamic",
    "TABLE_ROWS": 1e7,
    "AVG_ROW_LENGTH": 1337,
    "DATA_LENGTH": 90832896,
    "MAX_DATA_LENGTH": 0,
    "INDEX_LENGTH": 0,
    "DATA_FREE": 6291456,
    "AUTO_INCREMENT": null,
    "CREATE_TIME": null,
    "UPDATE_TIME": null,
    "CHECK_TIME": null,
    "TABLE_COLLATION": "utf8_general_ci",
    "CHECKSUM": null,
    "CREATE_OPTIONS": '',
    "TABLE_COMMENT": ''
  });
}


interface ColumnsRow {
  TABLE_CATALOG: string;
  TABLE_SCHEMA: string;
  TABLE_NAME: string;
  COLUMN_NAME: string;
  ORDINAL_POSITION: number,
  COLUMN_DEFAULT: string,
  IS_NULLABLE: string;
  DATA_TYPE: string;
  CHARACTER_MAXIMUM_LENGTH: number;
  CHARACTER_OCTET_LENGTH: number;
  NUMERIC_PRECISION: number,
  NUMERIC_SCALE: number,
  DATETIME_PRECISION: number,
  CHARACTER_SET_NAME: string;
  COLLATION_NAME: string;
  COLUMN_TYPE: string;
  COLUMN_KEY: string;
  EXTRA: string;
  PRIVILEGES: string;
  COLUMN_COMMENT: string;
  GENERATION_EXPRESSION: string;
}

let columnsData: ColumnsRow[] = [
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "COLUMNS",
    "COLUMN_NAME": "TABLE_CATALOG",
    "ORDINAL_POSITION": 1,
    "COLUMN_DEFAULT": "0",
    "IS_NULLABLE": "NO",
    "DATA_TYPE": "varchar",
    "CHARACTER_MAXIMUM_LENGTH": 512,
    "CHARACTER_OCTET_LENGTH": 1536,
    "NUMERIC_PRECISION": null,
    "NUMERIC_SCALE": null,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": "utf8",
    "COLLATION_NAME": "utf8_general_ci",
    "COLUMN_TYPE": "varchar(512)",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "COLUMNS",
    "COLUMN_NAME": "TABLE_SCHEMA",
    "ORDINAL_POSITION": 2,
    "COLUMN_DEFAULT": "0",
    "IS_NULLABLE": "NO",
    "DATA_TYPE": "varchar",
    "CHARACTER_MAXIMUM_LENGTH": 64,
    "CHARACTER_OCTET_LENGTH": 192,
    "NUMERIC_PRECISION": null,
    "NUMERIC_SCALE": null,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": "utf8",
    "COLLATION_NAME": "utf8_general_ci",
    "COLUMN_TYPE": "varchar(64)",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "COLUMNS",
    "COLUMN_NAME": "TABLE_NAME",
    "ORDINAL_POSITION": 3,
    "COLUMN_DEFAULT": "0",
    "IS_NULLABLE": "NO",
    "DATA_TYPE": "varchar",
    "CHARACTER_MAXIMUM_LENGTH": 64,
    "CHARACTER_OCTET_LENGTH": 192,
    "NUMERIC_PRECISION": null,
    "NUMERIC_SCALE": null,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": "utf8",
    "COLLATION_NAME": "utf8_general_ci",
    "COLUMN_TYPE": "varchar(64)",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "COLUMNS",
    "COLUMN_NAME": "COLUMN_NAME",
    "ORDINAL_POSITION": 4,
    "COLUMN_DEFAULT": "0",
    "IS_NULLABLE": "NO",
    "DATA_TYPE": "varchar",
    "CHARACTER_MAXIMUM_LENGTH": 64,
    "CHARACTER_OCTET_LENGTH": 192,
    "NUMERIC_PRECISION": null,
    "NUMERIC_SCALE": null,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": "utf8",
    "COLLATION_NAME": "utf8_general_ci",
    "COLUMN_TYPE": "varchar(64)",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "COLUMNS",
    "COLUMN_NAME": "ORDINAL_POSITION",
    "ORDINAL_POSITION": 5,
    "COLUMN_DEFAULT": "0",
    "IS_NULLABLE": "NO",
    "DATA_TYPE": "bigint",
    "CHARACTER_MAXIMUM_LENGTH": null,
    "CHARACTER_OCTET_LENGTH": null,
    "NUMERIC_PRECISION": 20,
    "NUMERIC_SCALE": 0,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": null,
    "COLLATION_NAME": null,
    "COLUMN_TYPE": "bigint(21) unsigned",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "COLUMNS",
    "COLUMN_NAME": "COLUMN_DEFAULT",
    "ORDINAL_POSITION": 6,
    "COLUMN_DEFAULT": null,
    "IS_NULLABLE": "YES",
    "DATA_TYPE": "longtext",
    "CHARACTER_MAXIMUM_LENGTH": 4294967295,
    "CHARACTER_OCTET_LENGTH": 4294967295,
    "NUMERIC_PRECISION": null,
    "NUMERIC_SCALE": null,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": "utf8",
    "COLLATION_NAME": "utf8_general_ci",
    "COLUMN_TYPE": "longtext",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "COLUMNS",
    "COLUMN_NAME": "IS_NULLABLE",
    "ORDINAL_POSITION": 7,
    "COLUMN_DEFAULT": "0",
    "IS_NULLABLE": "NO",
    "DATA_TYPE": "varchar",
    "CHARACTER_MAXIMUM_LENGTH": 3,
    "CHARACTER_OCTET_LENGTH": 9,
    "NUMERIC_PRECISION": null,
    "NUMERIC_SCALE": null,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": "utf8",
    "COLLATION_NAME": "utf8_general_ci",
    "COLUMN_TYPE": "varchar(3)",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "COLUMNS",
    "COLUMN_NAME": "DATA_TYPE",
    "ORDINAL_POSITION": 8,
    "COLUMN_DEFAULT": "0",
    "IS_NULLABLE": "NO",
    "DATA_TYPE": "varchar",
    "CHARACTER_MAXIMUM_LENGTH": 64,
    "CHARACTER_OCTET_LENGTH": 192,
    "NUMERIC_PRECISION": null,
    "NUMERIC_SCALE": null,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": "utf8",
    "COLLATION_NAME": "utf8_general_ci",
    "COLUMN_TYPE": "varchar(64)",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "COLUMNS",
    "COLUMN_NAME": "CHARACTER_MAXIMUM_LENGTH",
    "ORDINAL_POSITION": 9,
    "COLUMN_DEFAULT": null,
    "IS_NULLABLE": "YES",
    "DATA_TYPE": "bigint",
    "CHARACTER_MAXIMUM_LENGTH": null,
    "CHARACTER_OCTET_LENGTH": null,
    "NUMERIC_PRECISION": 20,
    "NUMERIC_SCALE": 0,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": null,
    "COLLATION_NAME": null,
    "COLUMN_TYPE": "bigint(21) unsigned",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "COLUMNS",
    "COLUMN_NAME": "CHARACTER_OCTET_LENGTH",
    "ORDINAL_POSITION": 10,
    "COLUMN_DEFAULT": null,
    "IS_NULLABLE": "YES",
    "DATA_TYPE": "bigint",
    "CHARACTER_MAXIMUM_LENGTH": null,
    "CHARACTER_OCTET_LENGTH": null,
    "NUMERIC_PRECISION": 20,
    "NUMERIC_SCALE": 0,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": null,
    "COLLATION_NAME": null,
    "COLUMN_TYPE": "bigint(21) unsigned",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "COLUMNS",
    "COLUMN_NAME": "NUMERIC_PRECISION",
    "ORDINAL_POSITION": 11,
    "COLUMN_DEFAULT": null,
    "IS_NULLABLE": "YES",
    "DATA_TYPE": "bigint",
    "CHARACTER_MAXIMUM_LENGTH": null,
    "CHARACTER_OCTET_LENGTH": null,
    "NUMERIC_PRECISION": 20,
    "NUMERIC_SCALE": 0,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": null,
    "COLLATION_NAME": null,
    "COLUMN_TYPE": "bigint(21) unsigned",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "COLUMNS",
    "COLUMN_NAME": "NUMERIC_SCALE",
    "ORDINAL_POSITION": 12,
    "COLUMN_DEFAULT": null,
    "IS_NULLABLE": "YES",
    "DATA_TYPE": "bigint",
    "CHARACTER_MAXIMUM_LENGTH": null,
    "CHARACTER_OCTET_LENGTH": null,
    "NUMERIC_PRECISION": 20,
    "NUMERIC_SCALE": 0,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": null,
    "COLLATION_NAME": null,
    "COLUMN_TYPE": "bigint(21) unsigned",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "COLUMNS",
    "COLUMN_NAME": "DATETIME_PRECISION",
    "ORDINAL_POSITION": 13,
    "COLUMN_DEFAULT": null,
    "IS_NULLABLE": "YES",
    "DATA_TYPE": "bigint",
    "CHARACTER_MAXIMUM_LENGTH": null,
    "CHARACTER_OCTET_LENGTH": null,
    "NUMERIC_PRECISION": 20,
    "NUMERIC_SCALE": 0,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": null,
    "COLLATION_NAME": null,
    "COLUMN_TYPE": "bigint(21) unsigned",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "COLUMNS",
    "COLUMN_NAME": "CHARACTER_SET_NAME",
    "ORDINAL_POSITION": 14,
    "COLUMN_DEFAULT": null,
    "IS_NULLABLE": "YES",
    "DATA_TYPE": "varchar",
    "CHARACTER_MAXIMUM_LENGTH": 32,
    "CHARACTER_OCTET_LENGTH": 96,
    "NUMERIC_PRECISION": null,
    "NUMERIC_SCALE": null,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": "utf8",
    "COLLATION_NAME": "utf8_general_ci",
    "COLUMN_TYPE": "varchar(32)",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "COLUMNS",
    "COLUMN_NAME": "COLLATION_NAME",
    "ORDINAL_POSITION": 15,
    "COLUMN_DEFAULT": null,
    "IS_NULLABLE": "YES",
    "DATA_TYPE": "varchar",
    "CHARACTER_MAXIMUM_LENGTH": 32,
    "CHARACTER_OCTET_LENGTH": 96,
    "NUMERIC_PRECISION": null,
    "NUMERIC_SCALE": null,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": "utf8",
    "COLLATION_NAME": "utf8_general_ci",
    "COLUMN_TYPE": "varchar(32)",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "COLUMNS",
    "COLUMN_NAME": "COLUMN_TYPE",
    "ORDINAL_POSITION": 16,
    "COLUMN_DEFAULT": null,
    "IS_NULLABLE": "NO",
    "DATA_TYPE": "longtext",
    "CHARACTER_MAXIMUM_LENGTH": 4294967295,
    "CHARACTER_OCTET_LENGTH": 4294967295,
    "NUMERIC_PRECISION": null,
    "NUMERIC_SCALE": null,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": "utf8",
    "COLLATION_NAME": "utf8_general_ci",
    "COLUMN_TYPE": "longtext",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "COLUMNS",
    "COLUMN_NAME": "COLUMN_KEY",
    "ORDINAL_POSITION": 17,
    "COLUMN_DEFAULT": "0",
    "IS_NULLABLE": "NO",
    "DATA_TYPE": "varchar",
    "CHARACTER_MAXIMUM_LENGTH": 3,
    "CHARACTER_OCTET_LENGTH": 9,
    "NUMERIC_PRECISION": null,
    "NUMERIC_SCALE": null,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": "utf8",
    "COLLATION_NAME": "utf8_general_ci",
    "COLUMN_TYPE": "varchar(3)",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "COLUMNS",
    "COLUMN_NAME": "EXTRA",
    "ORDINAL_POSITION": 18,
    "COLUMN_DEFAULT": "0",
    "IS_NULLABLE": "NO",
    "DATA_TYPE": "varchar",
    "CHARACTER_MAXIMUM_LENGTH": 30,
    "CHARACTER_OCTET_LENGTH": 90,
    "NUMERIC_PRECISION": null,
    "NUMERIC_SCALE": null,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": "utf8",
    "COLLATION_NAME": "utf8_general_ci",
    "COLUMN_TYPE": "varchar(30)",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "COLUMNS",
    "COLUMN_NAME": "PRIVILEGES",
    "ORDINAL_POSITION": 19,
    "COLUMN_DEFAULT": "0",
    "IS_NULLABLE": "NO",
    "DATA_TYPE": "varchar",
    "CHARACTER_MAXIMUM_LENGTH": 80,
    "CHARACTER_OCTET_LENGTH": 240,
    "NUMERIC_PRECISION": null,
    "NUMERIC_SCALE": null,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": "utf8",
    "COLLATION_NAME": "utf8_general_ci",
    "COLUMN_TYPE": "varchar(80)",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "COLUMNS",
    "COLUMN_NAME": "COLUMN_COMMENT",
    "ORDINAL_POSITION": 20,
    "COLUMN_DEFAULT": "0",
    "IS_NULLABLE": "NO",
    "DATA_TYPE": "varchar",
    "CHARACTER_MAXIMUM_LENGTH": 1024,
    "CHARACTER_OCTET_LENGTH": 3072,
    "NUMERIC_PRECISION": null,
    "NUMERIC_SCALE": null,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": "utf8",
    "COLLATION_NAME": "utf8_general_ci",
    "COLUMN_TYPE": "varchar(1024)",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "COLUMNS",
    "COLUMN_NAME": "GENERATION_EXPRESSION",
    "ORDINAL_POSITION": 21,
    "COLUMN_DEFAULT": null,
    "IS_NULLABLE": "NO",
    "DATA_TYPE": "longtext",
    "CHARACTER_MAXIMUM_LENGTH": 4294967295,
    "CHARACTER_OCTET_LENGTH": 4294967295,
    "NUMERIC_PRECISION": null,
    "NUMERIC_SCALE": null,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": "utf8",
    "COLLATION_NAME": "utf8_general_ci",
    "COLUMN_TYPE": "longtext",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "SCHEMATA",
    "COLUMN_NAME": "CATALOG_NAME",
    "ORDINAL_POSITION": 1,
    "COLUMN_DEFAULT": "0",
    "IS_NULLABLE": "NO",
    "DATA_TYPE": "varchar",
    "CHARACTER_MAXIMUM_LENGTH": 512,
    "CHARACTER_OCTET_LENGTH": 1536,
    "NUMERIC_PRECISION": null,
    "NUMERIC_SCALE": null,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": "utf8",
    "COLLATION_NAME": "utf8_general_ci",
    "COLUMN_TYPE": "varchar(512)",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "SCHEMATA",
    "COLUMN_NAME": "SCHEMA_NAME",
    "ORDINAL_POSITION": 2,
    "COLUMN_DEFAULT": "0",
    "IS_NULLABLE": "NO",
    "DATA_TYPE": "varchar",
    "CHARACTER_MAXIMUM_LENGTH": 64,
    "CHARACTER_OCTET_LENGTH": 192,
    "NUMERIC_PRECISION": null,
    "NUMERIC_SCALE": null,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": "utf8",
    "COLLATION_NAME": "utf8_general_ci",
    "COLUMN_TYPE": "varchar(64)",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "SCHEMATA",
    "COLUMN_NAME": "DEFAULT_CHARACTER_SET_NAME",
    "ORDINAL_POSITION": 3,
    "COLUMN_DEFAULT": "0",
    "IS_NULLABLE": "NO",
    "DATA_TYPE": "varchar",
    "CHARACTER_MAXIMUM_LENGTH": 32,
    "CHARACTER_OCTET_LENGTH": 96,
    "NUMERIC_PRECISION": null,
    "NUMERIC_SCALE": null,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": "utf8",
    "COLLATION_NAME": "utf8_general_ci",
    "COLUMN_TYPE": "varchar(32)",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "SCHEMATA",
    "COLUMN_NAME": "DEFAULT_COLLATION_NAME",
    "ORDINAL_POSITION": 4,
    "COLUMN_DEFAULT": "0",
    "IS_NULLABLE": "NO",
    "DATA_TYPE": "varchar",
    "CHARACTER_MAXIMUM_LENGTH": 32,
    "CHARACTER_OCTET_LENGTH": 96,
    "NUMERIC_PRECISION": null,
    "NUMERIC_SCALE": null,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": "utf8",
    "COLLATION_NAME": "utf8_general_ci",
    "COLUMN_TYPE": "varchar(32)",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "SCHEMATA",
    "COLUMN_NAME": "SQL_PATH",
    "ORDINAL_POSITION": 5,
    "COLUMN_DEFAULT": null,
    "IS_NULLABLE": "YES",
    "DATA_TYPE": "varchar",
    "CHARACTER_MAXIMUM_LENGTH": 512,
    "CHARACTER_OCTET_LENGTH": 1536,
    "NUMERIC_PRECISION": null,
    "NUMERIC_SCALE": null,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": "utf8",
    "COLLATION_NAME": "utf8_general_ci",
    "COLUMN_TYPE": "varchar(512)",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "TABLES",
    "COLUMN_NAME": "TABLE_CATALOG",
    "ORDINAL_POSITION": 1,
    "COLUMN_DEFAULT": "0",
    "IS_NULLABLE": "NO",
    "DATA_TYPE": "varchar",
    "CHARACTER_MAXIMUM_LENGTH": 512,
    "CHARACTER_OCTET_LENGTH": 1536,
    "NUMERIC_PRECISION": null,
    "NUMERIC_SCALE": null,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": "utf8",
    "COLLATION_NAME": "utf8_general_ci",
    "COLUMN_TYPE": "varchar(512)",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "TABLES",
    "COLUMN_NAME": "TABLE_SCHEMA",
    "ORDINAL_POSITION": 2,
    "COLUMN_DEFAULT": "0",
    "IS_NULLABLE": "NO",
    "DATA_TYPE": "varchar",
    "CHARACTER_MAXIMUM_LENGTH": 64,
    "CHARACTER_OCTET_LENGTH": 192,
    "NUMERIC_PRECISION": null,
    "NUMERIC_SCALE": null,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": "utf8",
    "COLLATION_NAME": "utf8_general_ci",
    "COLUMN_TYPE": "varchar(64)",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "TABLES",
    "COLUMN_NAME": "TABLE_NAME",
    "ORDINAL_POSITION": 3,
    "COLUMN_DEFAULT": "0",
    "IS_NULLABLE": "NO",
    "DATA_TYPE": "varchar",
    "CHARACTER_MAXIMUM_LENGTH": 64,
    "CHARACTER_OCTET_LENGTH": 192,
    "NUMERIC_PRECISION": null,
    "NUMERIC_SCALE": null,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": "utf8",
    "COLLATION_NAME": "utf8_general_ci",
    "COLUMN_TYPE": "varchar(64)",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "TABLES",
    "COLUMN_NAME": "TABLE_TYPE",
    "ORDINAL_POSITION": 4,
    "COLUMN_DEFAULT": "0",
    "IS_NULLABLE": "NO",
    "DATA_TYPE": "varchar",
    "CHARACTER_MAXIMUM_LENGTH": 64,
    "CHARACTER_OCTET_LENGTH": 192,
    "NUMERIC_PRECISION": null,
    "NUMERIC_SCALE": null,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": "utf8",
    "COLLATION_NAME": "utf8_general_ci",
    "COLUMN_TYPE": "varchar(64)",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "TABLES",
    "COLUMN_NAME": "ENGINE",
    "ORDINAL_POSITION": 5,
    "COLUMN_DEFAULT": null,
    "IS_NULLABLE": "YES",
    "DATA_TYPE": "varchar",
    "CHARACTER_MAXIMUM_LENGTH": 64,
    "CHARACTER_OCTET_LENGTH": 192,
    "NUMERIC_PRECISION": null,
    "NUMERIC_SCALE": null,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": "utf8",
    "COLLATION_NAME": "utf8_general_ci",
    "COLUMN_TYPE": "varchar(64)",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "TABLES",
    "COLUMN_NAME": "VERSION",
    "ORDINAL_POSITION": 6,
    "COLUMN_DEFAULT": null,
    "IS_NULLABLE": "YES",
    "DATA_TYPE": "bigint",
    "CHARACTER_MAXIMUM_LENGTH": null,
    "CHARACTER_OCTET_LENGTH": null,
    "NUMERIC_PRECISION": 20,
    "NUMERIC_SCALE": 0,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": null,
    "COLLATION_NAME": null,
    "COLUMN_TYPE": "bigint(21) unsigned",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "TABLES",
    "COLUMN_NAME": "ROW_FORMAT",
    "ORDINAL_POSITION": 7,
    "COLUMN_DEFAULT": null,
    "IS_NULLABLE": "YES",
    "DATA_TYPE": "varchar",
    "CHARACTER_MAXIMUM_LENGTH": 10,
    "CHARACTER_OCTET_LENGTH": 30,
    "NUMERIC_PRECISION": null,
    "NUMERIC_SCALE": null,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": "utf8",
    "COLLATION_NAME": "utf8_general_ci",
    "COLUMN_TYPE": "varchar(10)",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "TABLES",
    "COLUMN_NAME": "TABLE_ROWS",
    "ORDINAL_POSITION": 8,
    "COLUMN_DEFAULT": null,
    "IS_NULLABLE": "YES",
    "DATA_TYPE": "bigint",
    "CHARACTER_MAXIMUM_LENGTH": null,
    "CHARACTER_OCTET_LENGTH": null,
    "NUMERIC_PRECISION": 20,
    "NUMERIC_SCALE": 0,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": null,
    "COLLATION_NAME": null,
    "COLUMN_TYPE": "bigint(21) unsigned",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "TABLES",
    "COLUMN_NAME": "AVG_ROW_LENGTH",
    "ORDINAL_POSITION": 9,
    "COLUMN_DEFAULT": null,
    "IS_NULLABLE": "YES",
    "DATA_TYPE": "bigint",
    "CHARACTER_MAXIMUM_LENGTH": null,
    "CHARACTER_OCTET_LENGTH": null,
    "NUMERIC_PRECISION": 20,
    "NUMERIC_SCALE": 0,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": null,
    "COLLATION_NAME": null,
    "COLUMN_TYPE": "bigint(21) unsigned",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "TABLES",
    "COLUMN_NAME": "DATA_LENGTH",
    "ORDINAL_POSITION": 10,
    "COLUMN_DEFAULT": null,
    "IS_NULLABLE": "YES",
    "DATA_TYPE": "bigint",
    "CHARACTER_MAXIMUM_LENGTH": null,
    "CHARACTER_OCTET_LENGTH": null,
    "NUMERIC_PRECISION": 20,
    "NUMERIC_SCALE": 0,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": null,
    "COLLATION_NAME": null,
    "COLUMN_TYPE": "bigint(21) unsigned",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "TABLES",
    "COLUMN_NAME": "MAX_DATA_LENGTH",
    "ORDINAL_POSITION": 11,
    "COLUMN_DEFAULT": null,
    "IS_NULLABLE": "YES",
    "DATA_TYPE": "bigint",
    "CHARACTER_MAXIMUM_LENGTH": null,
    "CHARACTER_OCTET_LENGTH": null,
    "NUMERIC_PRECISION": 20,
    "NUMERIC_SCALE": 0,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": null,
    "COLLATION_NAME": null,
    "COLUMN_TYPE": "bigint(21) unsigned",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "TABLES",
    "COLUMN_NAME": "INDEX_LENGTH",
    "ORDINAL_POSITION": 12,
    "COLUMN_DEFAULT": null,
    "IS_NULLABLE": "YES",
    "DATA_TYPE": "bigint",
    "CHARACTER_MAXIMUM_LENGTH": null,
    "CHARACTER_OCTET_LENGTH": null,
    "NUMERIC_PRECISION": 20,
    "NUMERIC_SCALE": 0,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": null,
    "COLLATION_NAME": null,
    "COLUMN_TYPE": "bigint(21) unsigned",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "TABLES",
    "COLUMN_NAME": "DATA_FREE",
    "ORDINAL_POSITION": 13,
    "COLUMN_DEFAULT": null,
    "IS_NULLABLE": "YES",
    "DATA_TYPE": "bigint",
    "CHARACTER_MAXIMUM_LENGTH": null,
    "CHARACTER_OCTET_LENGTH": null,
    "NUMERIC_PRECISION": 20,
    "NUMERIC_SCALE": 0,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": null,
    "COLLATION_NAME": null,
    "COLUMN_TYPE": "bigint(21) unsigned",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "TABLES",
    "COLUMN_NAME": "AUTO_INCREMENT",
    "ORDINAL_POSITION": 14,
    "COLUMN_DEFAULT": null,
    "IS_NULLABLE": "YES",
    "DATA_TYPE": "bigint",
    "CHARACTER_MAXIMUM_LENGTH": null,
    "CHARACTER_OCTET_LENGTH": null,
    "NUMERIC_PRECISION": 20,
    "NUMERIC_SCALE": 0,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": null,
    "COLLATION_NAME": null,
    "COLUMN_TYPE": "bigint(21) unsigned",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "TABLES",
    "COLUMN_NAME": "CREATE_TIME",
    "ORDINAL_POSITION": 15,
    "COLUMN_DEFAULT": null,
    "IS_NULLABLE": "YES",
    "DATA_TYPE": "datetime",
    "CHARACTER_MAXIMUM_LENGTH": null,
    "CHARACTER_OCTET_LENGTH": null,
    "NUMERIC_PRECISION": null,
    "NUMERIC_SCALE": null,
    "DATETIME_PRECISION": 0,
    "CHARACTER_SET_NAME": null,
    "COLLATION_NAME": null,
    "COLUMN_TYPE": "datetime",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "TABLES",
    "COLUMN_NAME": "UPDATE_TIME",
    "ORDINAL_POSITION": 16,
    "COLUMN_DEFAULT": null,
    "IS_NULLABLE": "YES",
    "DATA_TYPE": "datetime",
    "CHARACTER_MAXIMUM_LENGTH": null,
    "CHARACTER_OCTET_LENGTH": null,
    "NUMERIC_PRECISION": null,
    "NUMERIC_SCALE": null,
    "DATETIME_PRECISION": 0,
    "CHARACTER_SET_NAME": null,
    "COLLATION_NAME": null,
    "COLUMN_TYPE": "datetime",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "TABLES",
    "COLUMN_NAME": "CHECK_TIME",
    "ORDINAL_POSITION": 17,
    "COLUMN_DEFAULT": null,
    "IS_NULLABLE": "YES",
    "DATA_TYPE": "datetime",
    "CHARACTER_MAXIMUM_LENGTH": null,
    "CHARACTER_OCTET_LENGTH": null,
    "NUMERIC_PRECISION": null,
    "NUMERIC_SCALE": null,
    "DATETIME_PRECISION": 0,
    "CHARACTER_SET_NAME": null,
    "COLLATION_NAME": null,
    "COLUMN_TYPE": "datetime",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "TABLES",
    "COLUMN_NAME": "TABLE_COLLATION",
    "ORDINAL_POSITION": 18,
    "COLUMN_DEFAULT": null,
    "IS_NULLABLE": "YES",
    "DATA_TYPE": "varchar",
    "CHARACTER_MAXIMUM_LENGTH": 32,
    "CHARACTER_OCTET_LENGTH": 96,
    "NUMERIC_PRECISION": null,
    "NUMERIC_SCALE": null,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": "utf8",
    "COLLATION_NAME": "utf8_general_ci",
    "COLUMN_TYPE": "varchar(32)",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "TABLES",
    "COLUMN_NAME": "CHECKSUM",
    "ORDINAL_POSITION": 19,
    "COLUMN_DEFAULT": null,
    "IS_NULLABLE": "YES",
    "DATA_TYPE": "bigint",
    "CHARACTER_MAXIMUM_LENGTH": null,
    "CHARACTER_OCTET_LENGTH": null,
    "NUMERIC_PRECISION": 20,
    "NUMERIC_SCALE": 0,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": null,
    "COLLATION_NAME": null,
    "COLUMN_TYPE": "bigint(21) unsigned",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "TABLES",
    "COLUMN_NAME": "CREATE_OPTIONS",
    "ORDINAL_POSITION": 20,
    "COLUMN_DEFAULT": null,
    "IS_NULLABLE": "YES",
    "DATA_TYPE": "varchar",
    "CHARACTER_MAXIMUM_LENGTH": 255,
    "CHARACTER_OCTET_LENGTH": 765,
    "NUMERIC_PRECISION": null,
    "NUMERIC_SCALE": null,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": "utf8",
    "COLLATION_NAME": "utf8_general_ci",
    "COLUMN_TYPE": "varchar(255)",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  },
  {
    "TABLE_CATALOG": "def",
    "TABLE_SCHEMA": "information_schema",
    "TABLE_NAME": "TABLES",
    "COLUMN_NAME": "TABLE_COMMENT",
    "ORDINAL_POSITION": 21,
    "COLUMN_DEFAULT": "0",
    "IS_NULLABLE": "NO",
    "DATA_TYPE": "varchar",
    "CHARACTER_MAXIMUM_LENGTH": 2048,
    "CHARACTER_OCTET_LENGTH": 6144,
    "NUMERIC_PRECISION": null,
    "NUMERIC_SCALE": null,
    "DATETIME_PRECISION": null,
    "CHARACTER_SET_NAME": "utf8",
    "COLLATION_NAME": "utf8_general_ci",
    "COLUMN_TYPE": "varchar(2048)",
    "COLUMN_KEY": '',
    "EXTRA": '',
    "PRIVILEGES": "select",
    "COLUMN_COMMENT": '',
    "GENERATION_EXPRESSION": ''
  }
];

function getDataType(type: PlyType): string {
  switch (type) {
    case 'BOOLEAN': return 'tinyint';
    case 'STRING': return 'varchar';
    case 'SET/STRING': return 'varchar';
    case 'NUMBER': return 'double';
    case 'TIME': return 'timestamp';
    default: return 'varchar';
  }
}

function getColumnType(type: PlyType): string {
  switch (type) {
    case 'BOOLEAN': return 'tinyint(1)';
    case 'STRING': return 'varchar(255)';
    case 'SET/STRING': return 'varchar(255)';
    case 'NUMBER': return 'double';
    case 'TIME': return 'timestamp';
    default: return 'varchar(255)';
  }
}

function addExternalToColumns(source: string, external: External, mysqlTypes: boolean): void {
  let { attributes } = external;
  for (let i = 0; i < attributes.length; i++) {
    let attribute = attributes[i];
    columnsData.push({
      "TABLE_CATALOG": "def",
      "TABLE_SCHEMA": DB_NAME,
      "TABLE_NAME": source,
      "COLUMN_NAME": attribute.name,
      "ORDINAL_POSITION": i + 1,
      "COLUMN_DEFAULT": null,
      "IS_NULLABLE": "YES",
      "DATA_TYPE": mysqlTypes ? getDataType(attribute.type) : attribute.type,
      "CHARACTER_MAXIMUM_LENGTH": 255,
      "CHARACTER_OCTET_LENGTH": 1020,
      "NUMERIC_PRECISION": null,
      "NUMERIC_SCALE": null,
      "DATETIME_PRECISION": null,
      "CHARACTER_SET_NAME": "utf8mb4",
      "COLLATION_NAME": "utf8mb4_bin",
      "COLUMN_TYPE": mysqlTypes ? getColumnType(attribute.type) : attribute.type,
      "COLUMN_KEY": '',
      "EXTRA": '',
      "PRIVILEGES": "select",
      "COLUMN_COMMENT": attribute.special || '',
      "GENERATION_EXPRESSION": ''
    });
  }
}

export function addExternal(source: string, external: External, mysqlTypes: boolean): void {
  addExternalToTables(source);
  addExternalToColumns(source, external, mysqlTypes);
}

export function getSchemataDataset() {
  return Dataset.fromJS(schemataData);
}

export function getTablesDataset() {
  return Dataset.fromJS(tablesData);
}

export function getColumnsDataset() {
  return Dataset.fromJS(columnsData);
}

